---
name: Go
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-10.15
            shasum: shasum -a 512
          - os: ubuntu-20.04
            shasum: sha512sum
          - os: ubuntu-20.04
            shasum: sha512sum
          - os: windows-2019
            shasum: sha512sum
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.0
      - name: Unit tests
        run: go test ./... -cover
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
      - name: Set p2iwd deliverable environment variable
        run: echo "p2iwd-deliverable=p2iwd-${{ matrix.os }}" >> $GITHUB_ENV
      - name: Use the value
        run: |
          echo "${{ env.p2iwd-deliverable }}"
      - name: Build
        run: ./scripts/build.sh
        env:
          p2iwd_DELIVERABLE: ${{ env.p2iwd-deliverable }}
          SHA512_CMD: ${{ matrix.shasum }}
      - name: Quality
        run: |
          docker run --rm -v "$PWD:/mnt" koalaman/shellcheck:v0.8.0 */*.sh -x
          docker run --rm -v ${PWD}:/data markdownlint/markdownlint:0.11.0 \
            README.md -s /data/.markdownlint.rb
          docker run --rm -v $(pwd):/app -w /app \
            golangci/golangci-lint:v1.44.2-alpine golangci-lint run -v
          pip install --user yamllint==1.26.3
          yamllint .
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
